export const data = [
    {name:"Abhish Tiwary"},
    {name:"Abraham Lincoln"},
    {name:"Akshay Kumar"},
    {name:"Balakrishna"},
    {name:"Chitti Babu"},
    {name:"Chiranjeeb Sahoo"},
    {name:"Chris Gayle"},
    {name:"Darshan Gaonkar"},
    {name:"Deepika Padukone"},
    {name:"Dimpul"},
    {name:"Disha Patani"},
    {name:"Elly Avram"},
    {name:"Farhan Akthar"},
    {name:"Ganesh Rao"},
    {name:"Hardhik Pandya"},
    {name:"Harsha Bhogle"},
    {name:"Irfan Khan"},
    {name:"Isa Guha"},
    {name:"Joydeep Nayak"},
    {name:"Kagiso Rabada"},
    {name:"Kiran Bedi"},
    {name:"Kumarswamy H D"},
    {name:"Lisa Ray"},
    {name:"Manoj Tiwary"},
    {name:"Narandra Kumar Nandula"},
    {name:"Nikhil Yellidiyappa"},
    {name:"Praveena Satish"},
    {name:"Raj Shekar"},
    {name:"Rohit Sharma"},
    {name:"Sagar Bidikar"},
    {name:"Shikhar Dhavan"},
    {name:"Sumeet Raikar"},
    {name:"Suresh Raina"},
    {name:"Tirumala Dhaba"},
    {name:"Urvashi Rautela"},
    {name:"Vikas Kumar"},
    {name:"Virak Kohli"},
    {name:"Yashwanth Singh"},
]